#!/bin/bash
### ---
### name: 'MAP_TO_REFERENCE:MAP_READS (SRR38117627)'
### outputs:
### - 'SRR38117627.sorted.bam'
### - 'SRR38117627.sorted.bam.bai'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    local last_err=$?
    local exit_status=${nxf_main_ret:=0}
    [[ ${exit_status} -eq 0 && ${nxf_unstage_ret:=0} -ne 0 ]] && exit_status=${nxf_unstage_ret:=0}
    [[ ${exit_status} -eq 0 && ${last_err} -ne 0 ]] && exit_status=${last_err}
    printf -- $exit_status > /Users/eugenianikonorova/Documents/ITMO/ITMO_study/Bioinf_Pipelines/work/7f/068afe3fdbc456e84bde34ed5195a8/.exitcode
    set +u
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /Users/eugenianikonorova/Documents/ITMO/ITMO_study/Bioinf_Pipelines/work/7f/068afe3fdbc456e84bde34ed5195a8/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f reference.fa.pac
    rm -f reference.fa.sa
    rm -f reference.fa.ann
    rm -f SRR38117627_trimmed_1.fastq.gz
    rm -f reference.fa.amb
    rm -f reference.fa
    rm -f reference.fa.fai
    rm -f reference.fa.bwt
    rm -f SRR38117627_trimmed_2.fastq.gz
    ln -s /Users/eugenianikonorova/Documents/ITMO/ITMO_study/Bioinf_Pipelines/work/36/302c22f10c4e99141bff315ba62ad1/reference.fa.pac reference.fa.pac
    ln -s /Users/eugenianikonorova/Documents/ITMO/ITMO_study/Bioinf_Pipelines/work/36/302c22f10c4e99141bff315ba62ad1/reference.fa.sa reference.fa.sa
    ln -s /Users/eugenianikonorova/Documents/ITMO/ITMO_study/Bioinf_Pipelines/work/36/302c22f10c4e99141bff315ba62ad1/reference.fa.ann reference.fa.ann
    ln -s /Users/eugenianikonorova/Documents/ITMO/ITMO_study/Bioinf_Pipelines/work/d5/36ee4618ff9fd8cfef78f669f8fbe3/SRR38117627_trimmed_1.fastq.gz SRR38117627_trimmed_1.fastq.gz
    ln -s /Users/eugenianikonorova/Documents/ITMO/ITMO_study/Bioinf_Pipelines/work/36/302c22f10c4e99141bff315ba62ad1/reference.fa.amb reference.fa.amb
    ln -s /Users/eugenianikonorova/Documents/ITMO/ITMO_study/Bioinf_Pipelines/work/36/302c22f10c4e99141bff315ba62ad1/reference.fa reference.fa
    ln -s /Users/eugenianikonorova/Documents/ITMO/ITMO_study/Bioinf_Pipelines/work/36/302c22f10c4e99141bff315ba62ad1/reference.fa.fai reference.fa.fai
    ln -s /Users/eugenianikonorova/Documents/ITMO/ITMO_study/Bioinf_Pipelines/work/36/302c22f10c4e99141bff315ba62ad1/reference.fa.bwt reference.fa.bwt
    ln -s /Users/eugenianikonorova/Documents/ITMO/ITMO_study/Bioinf_Pipelines/work/d5/36ee4618ff9fd8cfef78f669f8fbe3/SRR38117627_trimmed_2.fastq.gz SRR38117627_trimmed_2.fastq.gz
}

nxf_unstage_outputs() {
    true
}

nxf_unstage_controls() {
    true
}

nxf_unstage() {
    if [[ ${nxf_main_ret:=0} == 0 ]]; then
        (set -e -o pipefail; (nxf_unstage_outputs | tee -a .command.out) 3>&1 1>&2 2>&3 | tee -a .command.err)
        nxf_unstage_ret=$?
    fi
    nxf_unstage_controls
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /Users/eugenianikonorova/Documents/ITMO/ITMO_study/Bioinf_Pipelines/work/7f/068afe3fdbc456e84bde34ed5195a8/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
